server:
  port: 8080
info:
  name: "commonService"

snowflake:
  workerId: 1
  datacenterId: 0

spring:
  datasource:
    mmmydb1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.236.124.181:3306/double
      username: root
      password: qwe123
      connectionTimeout: 60000
      initialSize: 20
      minIdle: 5
      maxActive: 200
    dbbbbb2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.236.124.181:3306/double
      username: root
      password: qwe123
      connectionTimeout: 60000
      initialSize: 20
      minIdle: 5
      maxActive: 200
  redis:
    host: 10.236.124.181
    port: 6379
    password: test123
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: 50ms
  mvc:
    throw-exception-if-no-handler-found: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml

com:
  access:
    authInfo:
      username: username
      password: passw0rd
    openList:
      - /login/**
      - /v2/api-docs
#     swagger ui,线上只保留/v2/api-docs
      - /swagger-ui.html
      - /webjars/springfox-swagger-ui/**
      - /swagger-resources/**
      - /favicon*
    authList:
      - /captcha/**
      - /remote/**
      - /limit/**
      - /export/**
      - /enum/**
      - /job/**
    whiteList:
      - /snowflake/**


